### ISSUE TITLE
How to support Windows?

### ISSUE THREAD

**Issue by DRMacIver** [DRMacIver/conjecture#5]
The core testing implementation in Conjecture is very dependent on the ability to fork and somewhat dependent on the ability to do shared memory IPC between processes.

How should this work under Windows? I could use something like mingw for fork, and that might be fine, but it's not a great solution and it would be nice to have something more native.

**Comment by jbytheway** [comment]
As suggested in [this stackoverflow answer](http://stackoverflow.com/questions/1703890/how-can-i-create-a-process-in-a-portable-manner) you can either use #ifdefs and Windows native functions, or use some portability library such as [APR](https://apr.apache.org/docs/apr/1.5/group__apr__thread__proc.html).

If you want to know how to use the Windows native functions, then I suggest reading the source of some package which has already solved this problem (e.g. Python's subprocess or the aforementioned APR).

However, note that forking is (anecdotally) much slower on Windows than Linux, so this approach may be a performance problem.
