### ISSUE TITLE
documentation: 4 bytes to make an int64?

### ISSUE THREAD

**Issue by rboulton** [DRMacIver/conjecture#9]
In https://github.com/DRMacIver/conjecture/blob/master/docs/design.rst there is an example:

```python
def int64s():
  return byteblock(4).map(lambda b: int.from_bytes(b, 'big', signed=True))
````

Shouldn't this be `byteblock(8)`?

**Comment by DRMacIver** [comment]
oops. Yes it should. Thanks,
